import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'syp_language'

const translations = {
  en: {
    commonLanguage: 'Language',
    commonInstitution: 'Institution',
    commonLogout: 'Logout',
    commonMenu: 'Menu',
    commonClose: 'Close',
    commonExpandSidebar: 'Expand Sidebar',
    commonCollapseSidebar: 'Collapse Sidebar',
    commonLoading: 'Loading...',
    commonSettings: 'Settings',
    commonEmail: 'Email',
    commonFullName: 'Full Name',
    commonPan: 'PAN',
    commonAmount: 'Amount',
    commonRole: 'Role',
    commonStatus: 'Status',
    commonDateBs: 'Date (BS)',
    commonFiscalYearBs: 'Fiscal Year (BS)',
    commonTaxReturnBucket: 'Tax Return Bucket',
    commonBillUpload: 'Bill Upload',
    commonSelectedFile: 'Selected file',
    commonSessionExpired: 'Your session has expired. Please sign in again.',
    commonDateFormatError: 'Date must be in Nepali format YYYY-MM-DD.',
    commonDateHint: 'Enter BS date in YYYY-MM-DD format',
    authTagline: 'Simple financial UI for institutions in Nepal',
    authWelcomeBack: 'Welcome back',
    authSignInSubtitle: 'Sign in to continue to your institutional dashboard',
    authIdentifier: 'Email, Username, or PAN',
    authIdentifierPlaceholder: 'institution@example.com, username, or PAN',
    authPassword: 'Password',
    authPasswordPlaceholder: 'Enter password',
    authKeepSignedIn: 'Keep me signed in',
    authForgotPassword: 'Forgot password?',
    authSignIn: 'Sign In',
    authSessionSecure: 'Your session is protected with secure sign-in controls.',
    authNoAccount: 'No account?',
    authRegister: 'Register',
    authAlreadyRegistered: 'Already registered?',
    authCreateAccount: 'Create Account',
    authCreatePasswordPlaceholder: 'Create password',
    authReenterPasswordPlaceholder: 'Re-enter password',
    authErrSignIn: 'Unable to sign in. Please check your credentials.',
    authErrServerUnreachable: 'Unable to reach the server. Please ensure backend is running on http://127.0.0.1:8000.',
    authErrPanDigits: 'PAN must be 9 to 10 digits.',
    authErrPasswordMismatch: 'Password and confirm password do not match.',
    authErrCreateAccount: 'Unable to create account. Please try again.',
    authSuccessLogin: 'Logged in successfully.',
    authSuccessLogout: 'Logged out successfully.',
    authSuccessAccountRequested: 'Account request submitted. Please wait for admin verification before sign in.',
    authInstitutionName: 'Institution Name',
    authFullName: 'Full Name',
    authPanNumber: 'PAN Number',
    authConfirmPassword: 'Confirm Password',
    authRole: 'Role',
    authRoleHint: 'Business owner, accountant, and auditor signups require admin approval.',
    roleAdmin: 'Admin',
    roleBusinessOwner: 'Business Owner',
    roleAccountant: 'Accountant',
    roleAuditor: 'Auditor',
    placeholderInstitutionName: 'ABC School',
    placeholderFullName: 'Ram Sharma',
    placeholderInstitutionEmail: 'admin@institution.com',
    placeholderPanDigits: '9-10 digit PAN',
    placeholderPanVatDigits: '9-10 digit PAN/VAT',
    placeholderUserEmail: 'user@institution.com',
    placeholderMin8Chars: 'Minimum 8 characters',
    navDashboard: 'Dashboard',
    navSales: 'Sales',
    navPurchases: 'Purchases',
    navExpenses: 'Expenses',
    navReports: 'Reports',
    navAnalytics: 'Analytics',
    navAudit: 'Audit',
    navSettings: 'Settings',
    dashboardTitle: 'Dashboard',
    dashboardSubtitle: 'Overview of sales, expenses, taxes and profitability',
    dashboardLoading: 'Loading dashboard data...',
    dashboardTotalSales: 'Total Sales',
    dashboardTotalExpenses: 'Total Expenses',
    dashboardTotalVat: 'Total VAT',
    dashboardTotalTds: 'Total TDS',
    dashboardNetProfitLoss: 'Net Profit/Loss',
    dashboardSalesTrend: 'Sales Trend (Timeline)',
    dashboardExpenseTrend: 'Expense Trend (Timeline)',
    dashboardNoSalesData: 'No sales data yet',
    dashboardNoExpenseData: 'No expense data yet',
    dashboardPrintChart: 'Print Chart',
    dashboardInsights: 'Key Insights',
    dashboardTaxEfficiency: 'Tax Efficiency',
    dashboardProfitMargin: 'Profit Margin',
    dashboardVatStatus: 'VAT Status',
    dashboardTdsStatus: 'TDS Status',
    dashboardCashflow: 'Cash Flow Analysis',
    dashboardExpenseRatio: 'Expense Ratio',
    dashboardTrendUp: 'Trend: Upward',
    dashboardTrendDown: 'Trend: Downward',
    dashboardTrendFlat: 'Trend: Stable',
    dashboardNetPayable: 'Net Amount Payable to IRD',
    dashboardNetCredit: 'Net Credit Available',
    dashboardGrossMargin: 'Gross Margin',
    dashboardDetailedAnalysis: 'Detailed Financial Analysis',
    dashboardSalesDescription: 'Total revenue from all sales transactions',
    dashboardExpensesDescription: 'Total expenses across all categories (Salary, Operations, Capital)',
    dashboardVatDescription: 'Net VAT position: Output VAT minus Input VAT from purchases and expenses',
    dashboardTdsDescription: 'Total Tax Deducted at Source from salary and other eligible expenses',
    dashboardProfitDescription: 'Gross Profit minus all expenses and tax withholdings',
    dashboardChartPrintTitle: 'FinAncio Dashboard Report',
    salesTitle: 'Add Sales',
    salesSubtitle: 'Record sales transaction with tax preview',
    salesErrFetch: 'Unable to fetch sales details.',
    salesErrLoad: 'Unable to load sales details.',
    salesErrPanVat: 'Buyer PAN/VAT must be 9 to 10 digits.',
    salesErrSubmit: 'Unable to submit sales entry.',
    salesSuccessSubmit: 'Sales entry submitted successfully.',
    salesBuyerPanVat: 'Buyer PAN/VAT Number',
    salesTaxPreviewTitle: 'Tax Preview',
    salesOutputVat: 'Output VAT (13%)',
    salesTotalWithVat: 'Total With VAT',
    salesIrdModeNote: 'IRD mode: VAT enabled for sales, TDS not applied on sales entries.',
    salesSubmit: 'Submit Sales Entry',
    salesHideHistory: 'Hide Sales Entry History',
    salesViewHistory: 'View Sales Entry History',
    salesHistoryTitle: 'Sales Entry History',
    salesHistorySubtitle: 'Latest submitted sales entries.',
    salesNoEntries: 'No sales entries found yet.',
    purchasesTitle: 'Add Purchase',
    purchasesSubtitle: 'Capture purchase records with tax preview',
    purchasesErrFetch: 'Unable to fetch purchase details.',
    purchasesErrLoad: 'Unable to load purchase details.',
    purchasesErrPanVat: 'Supplier PAN/VAT must be 9 to 10 digits.',
    purchasesErrSubmit: 'Unable to submit purchase entry.',
    purchasesSuccessSubmit: 'Purchase entry submitted successfully.',
    purchasesSupplierPanVat: 'Supplier PAN/VAT Number',
    purchasesInputVat: 'Input VAT (13%)',
    purchasesTotalWithVat: 'Total With VAT',
    purchasesIrdModeNote: 'IRD mode: VAT credit tracked on purchases, TDS not applied on purchases.',
    purchasesSubmit: 'Submit Purchase Entry',
    purchasesHideHistory: 'Hide Purchase History',
    purchasesViewHistory: 'View Purchase History',
    purchasesHistoryTitle: 'Purchase Entry History',
    purchasesHistorySubtitle: 'Latest submitted purchase entries.',
    purchasesNoEntries: 'No purchase entries found yet.',
    expensesTitle: 'Add Expense',
    expensesSubtitle: 'Capture expense records with IRD-oriented tax preview',
    expensesErrFetch: 'Unable to fetch expense details.',
    expensesErrLoad: 'Unable to load expense details.',
    expensesErrPanVat: 'Vendor PAN/VAT must be 9 to 10 digits.',
    expensesErrSubmit: 'Unable to submit expense entry.',
    expensesSuccessSubmit: 'Expense entry submitted successfully.',
    expensesType: 'Expense Type',
    expensesVendorPanVat: 'Vendor PAN/VAT Number',
    expensesTdsRate: 'TDS Rate',
    expensesVat13: 'VAT (13%)',
    expensesTdsLabel: 'TDS',
    expensesTdsNa: 'N/A',
    expensesNetAfterTax: 'Net After Tax',
    expensesIrdNote: 'TDS is applied only for Salary and Other Expenses in this IRD mode.',
    expensesSubmit: 'Submit Expense Entry',
    expensesHideHistory: 'Hide Expense History',
    expensesViewHistory: 'View Expense History',
    expensesHistoryTitle: 'Expense Entry History',
    expensesHistorySubtitle: 'Latest submitted expense entries.',
    expensesNoEntries: 'No expense entries found yet.',
    expenseTypeSalary: 'Salary',
    expenseTypeOther: 'Other Expenses',
    expenseTypeOperational: 'Operational (No TDS)',
    expenseTypeCapital: 'Capital (No TDS)',
    tableType: 'Type',
    tableVat: 'VAT',
    tableTds: 'TDS',
    tableTotal: 'Total',
    tableBucket: 'Bucket',
    tableBuyerPanVat: 'Buyer PAN/VAT',
    tableSupplierPanVat: 'Supplier PAN/VAT',
    tableVendorPanVat: 'Vendor PAN/VAT',
    reportsTitle: 'Reports',
    reportsSubtitle: 'Generate financial summaries for your institution',
    reportsPeriodAll: 'All',
    reportsPeriodMonthly: 'Monthly',
    reportsPeriodQuarterly: 'Quarterly',
    reportsPeriodAnnual: 'Annual',
    reportsParticular: 'Particular',
    reportsPeriodLabel: 'Report Period',
    reportsQuarterLabel: 'Quarter',
    reportsQuarterQ1: 'Q1 (Shrawan-Kartik)',
    reportsQuarterQ2: 'Q2 (Mangsir-Falgun)',
    reportsQuarterQ3: 'Q3 (Chaitra-Asar)',
    reportsLoading: 'Loading report...',
    reportsWithholdingTitle: 'Withholding Certificate / Challan',
    reportsWithholdingSubtitle: 'UI placeholders for IRD-aligned print/export workflow.',
    reportsGenerateTdsCert: 'Generate TDS Certificate',
    reportsGenerateChallan: 'Generate Challan Slip',
    analyticsTitle: 'Analytics',
    analyticsSubtitle: 'Visual trends for sales, expenses and tax distribution',
    analyticsLoading: 'Loading analytics...',
    analyticsTaxDistribution: 'Tax Distribution',
    analyticsNoTaxData: 'No tax data yet',
    auditTitle: 'Audit Report',
    auditSubtitle: 'Print-friendly institutional financial summary',
    auditSection: 'Section',
    auditDetail: 'Detail',
    auditLocation: 'Kathmandu, Nepal',
    auditSummaryTitle: 'Structured Financial Summary',
    auditLoading: 'Loading audit data...',
    auditComplianceTitle: 'Compliance Notes',
    auditNoteVat: 'VAT is calculated at 13% in transaction previews.',
    auditNoteTds: 'TDS is configured for Salary and Other Expenses only.',
    auditNotePan: 'PAN/VAT number field validation is enabled on transaction forms.',
    auditNoteFiscal: 'Fiscal Year (BS) and return bucket tagging is available for records.',
    actionsExportPdf: 'Export PDF',
    actionsExportWord: 'Export Word',
    actionsPrintReport: 'Print Report',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Manage profile and system preferences',
    settingsAdminSubtitle: 'Account controls for approval and management',
    settingsManagerSubtitle: 'Business owner account controls',
    settingsRefreshData: 'Refresh Data',
    settingsPendingRequests: 'Pending Signup Requests',
    settingsAllAccounts: 'All Accounts',
    settingsAccessRequired: 'Access Required',
    settingsAccessRequiredMsg: 'Only admins and business owners can manage user accounts.',
    settingsCreateUserAdmin: 'Create User (Admin)',
    settingsCreateTeam: 'Create Team Account (Business Owner)',
    settingsCreateUser: 'Create User',
    settingsOwnerCreateHint: 'Business owners can create verified accountant and auditor accounts for their organization.',
    settingsInstitutionName: 'Institution Name',
    settingsPanNumber: 'PAN Number',
    settingsTemporaryPassword: 'Temporary Password',
    settingsErrNonJson: 'API returned non-JSON response. Check backend server and API proxy configuration.',
    settingsErrLoadPending: 'Unable to load pending users.',
    settingsErrLoadAccounts: 'Unable to load account information.',
    settingsErrCreateUser: 'Unable to create user.',
    settingsSuccessCreateUser: 'User account created and verified successfully.',
    settingsErrVerifyUser: 'Unable to verify user.',
    settingsSuccessVerifyUser: 'User verified successfully.',
    settingsErrDecline: 'Unable to decline signup request.',
    settingsSuccessDecline: 'Signup request declined successfully.',
    settingsLoadingPending: 'Loading pending users...',
    settingsLoadingAccounts: 'Loading account details...',
    settingsNoPending: 'No pending verification requests.',
    settingsNoAccounts: 'No accounts found.',
    settingsAccept: 'Accept',
    settingsDecline: 'Decline',
    settingsActions: 'Actions',
    settingsRequestedRole: 'Requested Role',
    settingsVerified: 'Verified',
    settingsPending: 'Pending',
  },
  ne: {
    commonLanguage: 'भाषा',
    commonInstitution: 'संस्था',
    commonLogout: 'लगआउट',
    commonMenu: 'मेनु',
    commonClose: 'बन्द गर्नुहोस्',
    commonExpandSidebar: 'साइडबार विस्तार गर्नुहोस्',
    commonCollapseSidebar: 'साइडबार सानो बनाउनुहोस्',
    commonLoading: 'लोड हुँदैछ...',
    commonSettings: 'सेटिङ्स',
    commonEmail: 'इमेल',
    commonFullName: 'पूरा नाम',
    commonPan: 'प्यान',
    commonAmount: 'रकम',
    commonRole: 'भूमिका',
    commonStatus: 'स्थिति',
    commonDateBs: 'मिति (वि.सं.)',
    commonFiscalYearBs: 'आर्थिक वर्ष (वि.सं.)',
    commonTaxReturnBucket: 'कर फिर्ता अवधि',
    commonBillUpload: 'बिल अपलोड',
    commonSelectedFile: 'छानिएको फाइल',
    commonSessionExpired: 'तपाईंको सेसन समाप्त भएको छ। कृपया फेरि साइन इन गर्नुहोस्।',
    commonDateFormatError: 'मिति नेपाली ढाँचा YYYY-MM-DD मा हुनुपर्छ।',
    commonDateHint: 'वि.सं. मिति YYYY-MM-DD ढाँचामा लेख्नुहोस्',
    authTagline: 'नेपालका संस्थाका लागि सरल वित्तीय प्रणाली',
    authWelcomeBack: 'फेरि स्वागत छ',
    authSignInSubtitle: 'संस्थागत ड्यासबोर्डमा जान साइन इन गर्नुहोस्',
    authIdentifier: 'इमेल, प्रयोगकर्ता नाम, वा प्यान',
    authIdentifierPlaceholder: 'institution@example.com, username, or PAN',
    authPassword: 'पासवर्ड',
    authPasswordPlaceholder: 'पासवर्ड लेख्नुहोस्',
    authKeepSignedIn: 'मलाई साइन इन नै राख्नुहोस्',
    authForgotPassword: 'पासवर्ड बिर्सनुभयो?',
    authSignIn: 'साइन इन',
    authSessionSecure: 'तपाईंको सेसन सुरक्षित साइन-इन नियन्त्रणद्वारा सुरक्षित छ।',
    authNoAccount: 'खाता छैन?',
    authRegister: 'दर्ता गर्नुहोस्',
    authAlreadyRegistered: 'पहिले नै दर्ता गर्नुभएको छ?',
    authCreateAccount: 'खाता बनाउनुहोस्',
    authCreatePasswordPlaceholder: 'पासवर्ड बनाउनुहोस्',
    authReenterPasswordPlaceholder: 'पासवर्ड फेरि लेख्नुहोस्',
    authErrSignIn: 'साइन इन गर्न सकिएन। कृपया विवरण जाँच गर्नुहोस्।',
    authErrServerUnreachable: 'सर्भरसँग जडान हुन सकेन। कृपया ब्याकएन्ड http://127.0.0.1:8000 मा चलेको छ कि छैन जाँच गर्नुहोस्।',
    authErrPanDigits: 'प्यान ९ देखि १० अङ्कको हुनुपर्छ।',
    authErrPasswordMismatch: 'पासवर्ड र पुष्टि पासवर्ड मेल खाँदैन।',
    authErrCreateAccount: 'खाता बनाउन सकिएन। कृपया पुन: प्रयास गर्नुहोस्।',
    authSuccessLogin: 'सफलतापूर्वक साइन इन भयो।',
    authSuccessLogout: 'सफलतापूर्वक लगआउट भयो।',
    authSuccessAccountRequested: 'खाता अनुरोध पठाइयो। साइन इन गर्नुअघि प्रशासक प्रमाणीकरणको प्रतीक्षा गर्नुहोस्।',
    authInstitutionName: 'संस्थाको नाम',
    authFullName: 'पूरा नाम',
    authPanNumber: 'प्यान नम्बर',
    authConfirmPassword: 'पासवर्ड पुन: लेख्नुहोस्',
    authRole: 'भूमिका',
    authRoleHint: 'व्यवसाय मालिक, लेखापाल, र लेखा परीक्षकको दर्ता प्रशासक स्वीकृतिपछि मात्र सक्रिय हुन्छ।',
    roleAdmin: 'प्रशासक',
    roleBusinessOwner: 'व्यवसाय मालिक',
    roleAccountant: 'लेखापाल',
    roleAuditor: 'लेखा परीक्षक',
    placeholderInstitutionName: 'एबीसी विद्यालय',
    placeholderFullName: 'राम शर्मा',
    placeholderInstitutionEmail: 'admin@institution.com',
    placeholderPanDigits: '९-१० अङ्कको प्यान',
    placeholderPanVatDigits: '९-१० अङ्कको PAN/VAT',
    placeholderUserEmail: 'user@institution.com',
    placeholderMin8Chars: 'कम्तीमा ८ अक्षर',
    navDashboard: 'ड्यासबोर्ड',
    navSales: 'बिक्री',
    navPurchases: 'खरिद',
    navExpenses: 'खर्च',
    navReports: 'रिपोर्ट',
    navAnalytics: 'विश्लेषण',
    navAudit: 'लेखा परीक्षण',
    navSettings: 'सेटिङ्स',
    dashboardTitle: 'ड्यासबोर्ड',
    dashboardSubtitle: 'बिक्री, खर्च, कर, र नाफा-नोक्सानीको सारांश',
    dashboardLoading: 'ड्यासबोर्ड डाटा लोड हुँदैछ...',
    dashboardTotalSales: 'कुल बिक्री',
    dashboardTotalExpenses: 'कुल खर्च',
    dashboardTotalVat: 'कुल VAT',
    dashboardTotalTds: 'कुल TDS',
    dashboardNetProfitLoss: 'शुद्ध नाफा/नोक्सानी',
    dashboardSalesTrend: 'बिक्री प्रवृत्ति (समय रेखा)',
    dashboardExpenseTrend: 'खर्च प्रवृत्ति (समय रेखा)',
    dashboardNoSalesData: 'अहिलेसम्म बिक्री डाटा छैन',
    dashboardNoExpenseData: 'अहिलेसम्म खर्च डाटा छैन',
    dashboardPrintChart: 'चार्ट प्रिन्ट गर्नुहोस्',
    dashboardInsights: 'मुख्य अन्तर्दृष्टि',
    dashboardTaxEfficiency: 'कर दक्षता',
    dashboardProfitMargin: 'नाफा मार्जिन',
    dashboardVatStatus: 'VAT स्थिति',
    dashboardTdsStatus: 'TDS स्थिति',
    dashboardCashflow: 'नगद प्रवाह विश्लेषण',
    dashboardExpenseRatio: 'खर्च अनुपात',
    dashboardTrendUp: 'प्रवृत्ति: ऊपरमुखी',
    dashboardTrendDown: 'प्रवृत्ति: तलमुखी',
    dashboardTrendFlat: 'प्रवृत्ति: स्थिर',
    dashboardNetPayable: 'IRD लाई तिर्नुपर्ने कुल रकम',
    dashboardNetCredit: 'उपलब्ध कुल क्रेडिट',
    dashboardGrossMargin: 'सकल मार्जिन',
    dashboardDetailedAnalysis: 'विस्तृत आर्थिक विश्लेषण',
    dashboardSalesDescription: 'सबै बिक्री लेनदेनबाट कुल राजस्व',
    dashboardExpensesDescription: 'सबै श्रेणीहरूमा कुल खर्च (तलब, सञ्चालन, पूँजीगत)',
    dashboardVatDescription: 'शुद्ध VAT स्थिति: आउटपुट VAT घटा खरिद र खर्चबाट इनपुट VAT',
    dashboardTdsDescription: 'तलब र अन्य योग्य खर्चबाट कुल कर विदहोल्डिङ',
    dashboardProfitDescription: 'सकल नाफा घटा सबै खर्च र कर विदहोल्डिङ',
    dashboardChartPrintTitle: 'FinAncio ड्यासबोर्ड रिपोर्ट',
    salesTitle: 'बिक्री थप्नुहोस्',
    salesSubtitle: 'कर पूर्वावलोकन सहित बिक्री विवरण राख्नुहोस्',
    salesErrFetch: 'बिक्री विवरण ल्याउन सकिएन।',
    salesErrLoad: 'बिक्री विवरण लोड गर्न सकिएन।',
    salesErrPanVat: 'खरिदकर्ताको PAN/VAT ९ देखि १० अङ्कको हुनुपर्छ।',
    salesErrSubmit: 'बिक्री प्रविष्टि पेश गर्न सकिएन।',
    salesSuccessSubmit: 'बिक्री प्रविष्टि सफलतापूर्वक पेश गरियो।',
    salesBuyerPanVat: 'खरिदकर्ताको PAN/VAT नम्बर',
    salesTaxPreviewTitle: 'कर पूर्वावलोकन',
    salesOutputVat: 'आउटपुट VAT (13%)',
    salesTotalWithVat: 'VAT सहित कुल',
    salesIrdModeNote: 'IRD मोड: बिक्रीमा VAT लागू हुन्छ, बिक्री प्रविष्टिमा TDS लागू हुँदैन।',
    salesSubmit: 'बिक्री प्रविष्टि पेश गर्नुहोस्',
    salesHideHistory: 'बिक्री इतिहास लुकाउनुहोस्',
    salesViewHistory: 'बिक्री इतिहास हेर्नुहोस्',
    salesHistoryTitle: 'बिक्री प्रविष्टि इतिहास',
    salesHistorySubtitle: 'हालैका बिक्री प्रविष्टिहरू।',
    salesNoEntries: 'अहिलेसम्म कुनै बिक्री प्रविष्टि भेटिएन।',
    purchasesTitle: 'खरिद थप्नुहोस्',
    purchasesSubtitle: 'कर पूर्वावलोकन सहित खरिद रेकर्ड राख्नुहोस्',
    purchasesErrFetch: 'खरिद विवरण ल्याउन सकिएन।',
    purchasesErrLoad: 'खरिद विवरण लोड गर्न सकिएन।',
    purchasesErrPanVat: 'आपूर्तिकर्ताको PAN/VAT ९ देखि १० अङ्कको हुनुपर्छ।',
    purchasesErrSubmit: 'खरिद प्रविष्टि पेश गर्न सकिएन।',
    purchasesSuccessSubmit: 'खरिद प्रविष्टि सफलतापूर्वक पेश गरियो।',
    purchasesSupplierPanVat: 'आपूर्तिकर्ताको PAN/VAT नम्बर',
    purchasesInputVat: 'इनपुट VAT (13%)',
    purchasesTotalWithVat: 'VAT सहित कुल',
    purchasesIrdModeNote: 'IRD मोड: खरिदमा VAT क्रेडिट ट्र्याक हुन्छ, खरिद प्रविष्टिमा TDS लागू हुँदैन।',
    purchasesSubmit: 'खरिद प्रविष्टि पेश गर्नुहोस्',
    purchasesHideHistory: 'खरिद इतिहास लुकाउनुहोस्',
    purchasesViewHistory: 'खरिद इतिहास हेर्नुहोस्',
    purchasesHistoryTitle: 'खरिद प्रविष्टि इतिहास',
    purchasesHistorySubtitle: 'हालैका खरिद प्रविष्टिहरू।',
    purchasesNoEntries: 'अहिलेसम्म कुनै खरिद प्रविष्टि भेटिएन।',
    expensesTitle: 'खर्च थप्नुहोस्',
    expensesSubtitle: 'IRD उन्मुख कर पूर्वावलोकन सहित खर्च रेकर्ड राख्नुहोस्',
    expensesErrFetch: 'खर्च विवरण ल्याउन सकिएन।',
    expensesErrLoad: 'खर्च विवरण लोड गर्न सकिएन।',
    expensesErrPanVat: 'विक्रेताको PAN/VAT ९ देखि १० अङ्कको हुनुपर्छ।',
    expensesErrSubmit: 'खर्च प्रविष्टि पेश गर्न सकिएन।',
    expensesSuccessSubmit: 'खर्च प्रविष्टि सफलतापूर्वक पेश गरियो।',
    expensesType: 'खर्च प्रकार',
    expensesVendorPanVat: 'विक्रेताको PAN/VAT नम्बर',
    expensesTdsRate: 'TDS दर',
    expensesVat13: 'VAT (13%)',
    expensesTdsLabel: 'TDS',
    expensesTdsNa: 'लागू हुँदैन',
    expensesNetAfterTax: 'करपछि शुद्ध रकम',
    expensesIrdNote: 'यस IRD मोडमा TDS केवल तलब र अन्य खर्चमा लागू हुन्छ।',
    expensesSubmit: 'खर्च प्रविष्टि पेश गर्नुहोस्',
    expensesHideHistory: 'खर्च इतिहास लुकाउनुहोस्',
    expensesViewHistory: 'खर्च इतिहास हेर्नुहोस्',
    expensesHistoryTitle: 'खर्च प्रविष्टि इतिहास',
    expensesHistorySubtitle: 'हालैका खर्च प्रविष्टिहरू।',
    expensesNoEntries: 'अहिलेसम्म कुनै खर्च प्रविष्टि भेटिएन।',
    expenseTypeSalary: 'तलब',
    expenseTypeOther: 'अन्य खर्च',
    expenseTypeOperational: 'सञ्चालन (TDS लागू हुँदैन)',
    expenseTypeCapital: 'पूँजीगत (TDS लागू हुँदैन)',
    tableType: 'प्रकार',
    tableVat: 'VAT',
    tableTds: 'TDS',
    tableTotal: 'कुल',
    tableBucket: 'अवधि',
    tableBuyerPanVat: 'खरिदकर्ता PAN/VAT',
    tableSupplierPanVat: 'आपूर्तिकर्ता PAN/VAT',
    tableVendorPanVat: 'विक्रेता PAN/VAT',
    reportsTitle: 'रिपोर्ट',
    reportsSubtitle: 'तपाईंको संस्थाका लागि वित्तीय सारांश तयार गर्नुहोस्',
    reportsPeriodAll: 'सबै',
    reportsPeriodMonthly: 'मासिक',
    reportsPeriodQuarterly: 'त्रैमासिक',
    reportsPeriodAnnual: 'वार्षिक',
    reportsParticular: 'विवरण',
    reportsPeriodLabel: 'रिपोर्ट अवधि',
    reportsQuarterLabel: 'त्रैमासिक',
    reportsQuarterQ1: 'Q1 (श्रावण-कार्तिक)',
    reportsQuarterQ2: 'Q2 (मंसिर-फाल्गुण)',
    reportsQuarterQ3: 'Q3 (चैत्र-आषाढ)',
    reportsLoading: 'रिपोर्ट लोड हुँदैछ...',
    reportsWithholdingTitle: 'विदहोल्डिङ प्रमाणपत्र / चलान',
    reportsWithholdingSubtitle: 'IRD-अनुरूप प्रिन्ट/निर्यात कार्यप्रवाहका लागि UI स्थानधारक।',
    reportsGenerateTdsCert: 'TDS प्रमाणपत्र बनाउनुहोस्',
    reportsGenerateChallan: 'चलान स्लिप बनाउनुहोस्',
    analyticsTitle: 'विश्लेषण',
    analyticsSubtitle: 'बिक्री, खर्च र कर वितरणका दृश्य प्रवृत्तिहरू',
    analyticsLoading: 'विश्लेषण लोड हुँदैछ...',
    analyticsTaxDistribution: 'कर वितरण',
    analyticsNoTaxData: 'अहिलेसम्म कर डाटा छैन',
    auditTitle: 'लेखा परीक्षण रिपोर्ट',
    auditSubtitle: 'प्रिन्ट गर्न मिल्ने संस्थागत वित्तीय सारांश',
    auditSection: 'खण्ड',
    auditDetail: 'विवरण',
    auditLocation: 'काठमाडौँ, नेपाल',
    auditSummaryTitle: 'संरचित वित्तीय सारांश',
    auditLoading: 'लेखा परीक्षण डाटा लोड हुँदैछ...',
    auditComplianceTitle: 'अनुपालन टिप्पणीहरू',
    auditNoteVat: 'लेनदेन पूर्वावलोकनमा VAT 13% मा गणना गरिन्छ।',
    auditNoteTds: 'TDS केवल तलब र अन्य खर्चका लागि कन्फिगर गरिएको छ।',
    auditNotePan: 'लेनदेन फारमहरूमा PAN/VAT नम्बर प्रमाणीकरण सक्षम छ।',
    auditNoteFiscal: 'रेकर्डका लागि आर्थिक वर्ष (वि.सं.) र फिर्ता अवधि ट्याग उपलब्ध छ।',
    actionsExportPdf: 'PDF निर्यात',
    actionsExportWord: 'Word निर्यात',
    actionsPrintReport: 'रिपोर्ट प्रिन्ट',
    settingsTitle: 'सेटिङ्स',
    settingsSubtitle: 'प्रोफाइल र प्रणाली प्राथमिकता व्यवस्थापन',
    settingsAdminSubtitle: 'स्वीकृति र व्यवस्थापनका लागि खाता नियन्त्रण',
    settingsManagerSubtitle: 'व्यवसाय मालिक खाता नियन्त्रण',
    settingsRefreshData: 'डाटा रिफ्रेस गर्नुहोस्',
    settingsPendingRequests: 'प्रतीक्षारत दर्ता अनुरोधहरू',
    settingsAllAccounts: 'सबै खाताहरू',
    settingsAccessRequired: 'अनुमति आवश्यक',
    settingsAccessRequiredMsg: 'प्रशासक र व्यवसाय मालिकले मात्र प्रयोगकर्ता व्यवस्थापन गर्न सक्छन्।',
    settingsCreateUserAdmin: 'प्रयोगकर्ता बनाउनुहोस् (प्रशासक)',
    settingsCreateTeam: 'टोली खाता बनाउनुहोस् (व्यवसाय मालिक)',
    settingsCreateUser: 'प्रयोगकर्ता बनाउनुहोस्',
    settingsOwnerCreateHint: 'व्यवसाय मालिकले आफ्नो संस्थाका लागि प्रमाणित लेखापाल र लेखा परीक्षक खाता बनाउन सक्छन्।',
    settingsInstitutionName: 'संस्थाको नाम',
    settingsPanNumber: 'प्यान नम्बर',
    settingsTemporaryPassword: 'अस्थायी पासवर्ड',
    settingsErrNonJson: 'API ले JSON बाहेकको प्रतिक्रिया दियो। ब्याकएन्ड सर्भर र API प्रोक्सी कन्फिगरेसन जाँच गर्नुहोस्।',
    settingsErrLoadPending: 'प्रतीक्षारत प्रयोगकर्ता लोड गर्न सकिएन।',
    settingsErrLoadAccounts: 'खाता जानकारी लोड गर्न सकिएन।',
    settingsErrCreateUser: 'प्रयोगकर्ता बनाउन सकिएन।',
    settingsSuccessCreateUser: 'प्रयोगकर्ता खाता सफलतापूर्वक बनाइयो र प्रमाणित गरियो।',
    settingsErrVerifyUser: 'प्रयोगकर्ता प्रमाणित गर्न सकिएन।',
    settingsSuccessVerifyUser: 'प्रयोगकर्ता सफलतापूर्वक प्रमाणित गरियो।',
    settingsErrDecline: 'दर्ता अनुरोध अस्वीकृत गर्न सकिएन।',
    settingsSuccessDecline: 'दर्ता अनुरोध सफलतापूर्वक अस्वीकृत गरियो।',
    settingsLoadingPending: 'प्रतीक्षारत प्रयोगकर्ता लोड हुँदैछन्...',
    settingsLoadingAccounts: 'खाता विवरण लोड हुँदैछ...',
    settingsNoPending: 'प्रमाणीकरणका लागि कुनै अनुरोध छैन।',
    settingsNoAccounts: 'खाता भेटिएन।',
    settingsAccept: 'स्वीकृत',
    settingsDecline: 'अस्वीकृत',
    settingsActions: 'कार्यहरू',
    settingsRequestedRole: 'अनुरोध गरिएको भूमिका',
    settingsVerified: 'प्रमाणित',
    settingsPending: 'प्रतीक्षारत',
  },
}

const LanguageContext = createContext(null)

// eslint-disable-next-line react-refresh/only-export-components
export const LANGUAGE_OPTIONS = [
  { value: 'en', label: 'English' },
  { value: 'ne', label: 'नेपाली' },
]

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem(STORAGE_KEY)
    return saved === 'ne' || saved === 'en' ? saved : 'en'
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.lang = language === 'ne' ? 'ne-NP' : 'en'
    document.body.setAttribute('data-language', language)
  }, [language])

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key) => translations[language]?.[key] || translations.en[key] || key,
    }),
    [language]
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
