# Generated by Django 5.1.6 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_expenseentry_purchaseentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("accountant", "Accountant"),
                    ("auditor", "Auditor"),
                ],
                default="accountant",
                max_length=20,
            ),
        ),
    ]
