# Generated by Django 5.1.6 on 2026-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_verified_and_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(max_length=10),
        ),
    ]
